service: feed-connector
app: patron-feed
org: gtwright

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true
    basePath: ${env:BASE_PATH}

functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /
          method: get
  iCalFeed:
    handler: handler.ical
    events:
      - http:
          path: ical
          method: get
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
